# Generated by Django 5.1.3 on 2024-12-04 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernewskill',
            unique_together={('user', 'skill')},
        ),
    ]
