# Generated by Django 5.1.3 on 2024-12-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0002_alter_usernewskill_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newskill',
            unique_together={('category', 'subcategory', 'name')},
        ),
    ]
