# Generated by Django 5.1.4 on 2025-01-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0007_democategory_demonewskill_demoskillrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoskillrating',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='demoskillrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='demosubcategory',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='usernewskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usernewskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='usernewskill',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='newskill',
            unique_together=set(),
        ),
        migrations.RenameModel(
            old_name='DemoCategory',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='user_skills.category')),
            ],
        ),
        migrations.AlterField(
            model_name='newskill',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_skills.subcategory'),
        ),
        migrations.DeleteModel(
            name='DemoNewSkill',
        ),
        migrations.DeleteModel(
            name='DemoSkillRating',
        ),
        migrations.DeleteModel(
            name='DemoSubcategory',
        ),
        migrations.DeleteModel(
            name='UserNewSkill',
        ),
        migrations.RemoveField(
            model_name='newskill',
            name='category',
        ),
    ]
