# Generated by Django 5.1.4 on 2025-01-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0008_remove_demoskillrating_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newskill',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategories', to='user_skills.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_categories', to='user_skills.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubcategoryNewSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorysubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory_newskills', to='user_skills.categorysubcategory')),
                ('new_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newskill_subcategories', to='user_skills.newskill')),
            ],
        ),
    ]
