# Generated by Django 5.1.4 on 2025-01-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0009_remove_newskill_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrating',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='user_skills.categorysubcategorynewskill'),
        ),
    ]
