# Generated by Django 5.1.4 on 2025-01-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0010_alter_skillrating_skill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together={('category', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategorynewskill',
            unique_together={('categorysubcategory', 'new_skill')},
        ),
    ]
