# Generated by Django 5.1.4 on 2025-01-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0013_certificate_certificateusermap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateUserMap',
        ),
    ]
