# Generated by Django 5.1.4 on 2025-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0015_certificateusermap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateusermap',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificateusermap',
            name='issue_date',
            field=models.DateField(blank=True),
        ),
    ]
