# Generated by Django 5.1.4 on 2025-01-20 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0016_alter_certificateusermap_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificateusermap',
            constraint=models.UniqueConstraint(fields=('user_id', 'cert_id'), name='unique_user_certificate'),
        ),
    ]
