# Generated by Django 5.1.4 on 2025-01-20 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0017_certificateusermap_unique_user_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificateusermap',
            name='unique_user_certificate',
        ),
        migrations.AddConstraint(
            model_name='certificateusermap',
            constraint=models.UniqueConstraint(fields=('user_id', 'cert_id', 'issue_date', 'status'), name='unique_user_certificate'),
        ),
    ]
