# Generated by Django 5.1.4 on 2025-01-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0019_organization_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_tree',
            name='empname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
