# Generated by Django 5.1.4 on 2025-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_skills', '0020_alter_organization_tree_empname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillrating',
            name='review',
        ),
        migrations.AddField(
            model_name='skillrating',
            name='mgrreview',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
